fix deployment files

diff --git a/.github/workflows/cd-main.yml b/.github/workflows/cd-main.yml
--- a/.github/workflows/cd-main.yml
+++ b/.github/workflows/cd-main.yml
@@ -4,8 +4,8 @@ on:
     branches: ['main']
 
 env:
-  REPOSITORY: ${{ github.repository }}
-  GHCR_URL: ghcr.io
+  REPOSITORY: ${{ github.repository }} # <user>/<repo>
+  GHCR_URL: ghcr.io # GitHub Container Registry
 
 jobs:
   cd:
@@ -29,6 +29,13 @@ jobs:
           echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
           echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
 
+      # 1º Crear Token de Acceso Personal:
+      #    GitHub → Settings → Developer settings → Personal access tokens → Generate new token (classic)
+      #    Permisos mínimos: write:packages, read:packages, delete:packages, repo
+      #
+      # 2º Crear secret en GitHub:
+      #    Repo → Settings → Secrets and variables → Actions → New repository secret
+      #    Name: GHCR_PERSONAL_ACCESS_TOKEN, Value: <tu token>
       - name: 📦 Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -45,8 +52,11 @@ jobs:
             ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
             ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest
 
-      - name: 🚀 Deploy on Render
-        run: |
-          curl --fail -X POST "https://api.render.com/deploy/${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}" \
-          && echo "✅ Deployment succeeded" \
-          || (echo "❌ Deployment failed" && exit 1)
+      # 🌐 Render Deployment
+      # 1. En Render: Web Service → Settings → Deploy Hook → copiar el token
+      # 2. En GitHub: Settings → Secrets and variables → Actions → crear secret: RENDER_DEPLOY_HOOK_TOKEN
+      #- name: 🚀 Deploy on Render
+      #  run: |
+      #    curl --fail -X POST "https://api.render.com/deploy/${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}" \
+      #    && echo "✅ Deployment succeeded" \
+      #    || (echo "❌ Deployment failed" && exit 1)
